print("nhapa: ");
a =  int(input());
b =  int(input());
print("a + b =", a + b);
print("a - b =", a - b);
print("a * b =", a * b);
print("a // b =", a // b);
print("a ** b =", a ** b);
print("a > b =", a > b);
print("a & b =", a & b);
print("a | b =", a | b);
print("a ^ b =", a ^ b);
print("~ a =", ~a);
print("(a >> 5) =", a>>5);